version: "3.8"
services:
  frontend:
    build: ./client
    ports:
      - "3000:3000"
    networks:
      - test
  backend:
    build: ./react-backend
    ports:
      - "3001:3001"
    networks: 
     - test

networks:
  test:
